name: point_of_sales
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.6.6
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  fl_chart: ^0.64.0
  animated_bottom_navigation_bar: ^1.3.0
  auto_size_text: ^3.0.0
  flutter_speed_dial: ^7.0.0
  badges: ^3.1.1
  grouped_list: ^5.1.2
  pdf: ^3.10.6
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Regular.ttf
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Poppins-Black.ttf
          weight: 900


